# The End Defines The Means and The Start

All beginnings are difficult. In data science, one reason making all the beginnings harder is that we just don't know what sort of question we're trying to answer. That's why we often run into the dilemma of "Moving The Goalposts". It's not necessarily wrong but it can become frustrated if you get asked to go north first and south later. But then the answer is in fact next to you. 

For data manipulation and management, we should think about the end product first and do more reverse thinking than forward thinking. For example, what sort of end products do we commonly need to include in the end product? Data visualisation? Poster? Coding sharing? Data Management? Journal article write-up? The key point is that how we can improve the workflow across need end and we can easily generate and reproduce our end product.    

```{r nice-fig, fig.cap='Here is a nice figure!', out.width='80%', fig.asp=.75, fig.align='center'}
par(mar = c(4, 4, .1, .1))
plot(pressure, type = 'b', pch = 19)
```

