# Introduction to Machine Learning

There're two main tribes of machine learning. One tribe is called _supervised learning_ and it's focused on problems with predictive nature. The other one is called _unsupervised learning_ and it's focused on problems with descriptive nature.

## Supervised learning

The idea of supervised learning is that given a set of attributes or features of the objects or targets, the model is then trained to generate accurate prediction on the objects or targets. The idea of supervision refers to the fact that the target values provide a supervisory role, which means that the learning algorithm is expected to go through a set of cases where the target an its features are both presented. The learning algorithm (such as tree algorithm, neural networks) will then determine the right combination or optimisation among the features (such as feature engineering) to predict the targets.  

Some of the common challenges involved with supervised learning are including, 
- To predict the likelihood of  customer churning over a certain period of time through a set of customer attributes;
- To predict the likelihood of employee retention of using a range of employee and workplace attributes;
- To predict the transaction price of real estates through a range of home attributes;
- To predict the re-admission of the patients through a set of patient attributes and symptoms. 

Some of the family members are expected to exist in machine learning
- Y: Outcome measure (or response, target, dependent variable)

	- Y is numeric. When the outcome measure is numeric / continuous outcome, this is regarded as regression challenge. For example, Average home sales price as a function of year built and total square footage. 

	- Y is categorical. When the outcome measure is categorical outcome, this is regarded as classification challenge. For example, Did a customer redeem a coupon . 

- X: Feature measure (or predictor, attribute, independent variable)
- training data
- testing data


## Unsupervised learning

In essence, unsupervised learning is concerned with identifying groups in a data set. The groups may be defined by the rows (i.e., clustering) or the columns (i.e., dimension reduction). The goal of clustering is to segment observations into similar groups based on the observed variables; for example, to divide consumers into different homogeneous groups, a process known as market segmentation. In dimension reduction, we are often concerned with reducing the number of variables in a data set. 

Unsupervised learning is often performed as part of an exploratory data analysis (EDA). However, the exercise tends to be more subjective, and there is no simple goal for the analysis, such as prediction of a response. 
- Divide consumers into different homogeneous groups so that tailored marketing strategies can be developed and deployed for each segment.
- Identify groups of online shoppers with similar browsing and purchase histories, as well as items that are of particular interest to the shoppers within each group. Then an individual shopper can be preferentially shown the items in which he or she is particularly likely to be interested, based on the purchase histories of similar shoppers. 
- Identify products that have similar purchasing behavior so that managers can manage them as product groups.

