--- 
title: Introduction to Data Science with R 🙀
author:
  - name: Ning Lu
    affiliation: Bradford Institute of Health Research (BIHR)
  - name: Bradford Teaching Hospitals NHS Foundation Trust (BTHFT)
    affiliation: Centre for Applied Education Research (CAER)
  - name: Leeds Institute for Data Analytics, University of Leeds (LIDA)
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
description: "This is a minimal example of training people to start doing data analytic in R."
---

# Heroes Are Made  

> A hero is somebody who voluntarily walks into the unknown. To become a hero in R, you have to voluntarily walk into the unknown of R and the world of data science.  

## Goal

This is a R learning and sharing platform. You can learn how to use R to manage your data manipulation and management here. I will gradually build in more data science materials here. My ultimate goal is to consolidate all the R learning experience and share them through this platform. 

While the platform is open to anyone who is interested in learning data manipulation and management with R, the primary target audience is members of Bradford Institute of Health Research (BIHR), Bradford Teaching Hospitals NHS Foundation Trust (BTHFT), Centre for Applied Education Research (CAER) and Leeds Data Science Society. 

When you visit here, I don't expect you to have a lot of R knowledge. However, I'd hope that when you leave here, you'd at least learn something new - something would make you a hero 😎 for a while. 